version: "3.9"

services:
  db:
    image: postgres:16
    container_name: denso_db_local
    restart: always
    environment:
      POSTGRES_USER: denso
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: denso_forecast
    ports:
      - "5432:5432"
    volumes:
      - denso_db_data_local:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: denso_pgadmin_local
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  denso_db_data_local: